jenkins:
  systemMessage: "DiSc21 Jenkins server configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin 
         password: qwerty
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

jobs:
  - script:
    multibranchPipelineJob('configuration-as-code') {
      branchSources {
        git {
          id = 'configuration-as-code'
          remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
        }
      }
    }

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: http://localhost:8080/
  themeManager:
    disableUserThemes: true
    theme: "dark"

